//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/Skrips/PlayerMovment/AtionMaping/Camra Controll Actions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @CamraControllActions : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @CamraControllActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""Camra Controll Actions"",
    ""maps"": [
        {
            ""name"": ""CamraNew"",
            ""id"": ""fae89dd7-7dff-43d0-ba7c-50315a29b460"",
            ""actions"": [
                {
                    ""name"": ""Movement"",
                    ""type"": ""Value"",
                    ""id"": ""e2326df0-25db-454d-b206-ced89552e06a"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""RotateCamera"",
                    ""type"": ""Value"",
                    ""id"": ""b1c9039a-0eeb-4ebb-9332-93c7f1ce1f69"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""ZoomCamera"",
                    ""type"": ""Value"",
                    ""id"": ""cdee380d-76e2-4412-bb97-3f3bfadd375a"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""be36ac72-7cd5-4962-94e9-2ee9b4047a3f"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""84d32895-247b-434d-8303-b27fdb13fd76"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""9058cb84-87ea-4dc8-9265-78ecbe62cbb0"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""0c85eb87-a05e-4e58-931b-039e00d989a0"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""e9d2ad32-b0df-47df-a8f3-44ee6235bec5"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""c8582350-44af-4568-a622-34050ea0559b"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RotateCamera"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c03b212b-9020-4272-b140-c10dca68c6c5"",
                    ""path"": ""<Mouse>/scroll"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ZoomCamera"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // CamraNew
        m_CamraNew = asset.FindActionMap("CamraNew", throwIfNotFound: true);
        m_CamraNew_Movement = m_CamraNew.FindAction("Movement", throwIfNotFound: true);
        m_CamraNew_RotateCamera = m_CamraNew.FindAction("RotateCamera", throwIfNotFound: true);
        m_CamraNew_ZoomCamera = m_CamraNew.FindAction("ZoomCamera", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // CamraNew
    private readonly InputActionMap m_CamraNew;
    private ICamraNewActions m_CamraNewActionsCallbackInterface;
    private readonly InputAction m_CamraNew_Movement;
    private readonly InputAction m_CamraNew_RotateCamera;
    private readonly InputAction m_CamraNew_ZoomCamera;
    public struct CamraNewActions
    {
        private @CamraControllActions m_Wrapper;
        public CamraNewActions(@CamraControllActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Movement => m_Wrapper.m_CamraNew_Movement;
        public InputAction @RotateCamera => m_Wrapper.m_CamraNew_RotateCamera;
        public InputAction @ZoomCamera => m_Wrapper.m_CamraNew_ZoomCamera;
        public InputActionMap Get() { return m_Wrapper.m_CamraNew; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(CamraNewActions set) { return set.Get(); }
        public void SetCallbacks(ICamraNewActions instance)
        {
            if (m_Wrapper.m_CamraNewActionsCallbackInterface != null)
            {
                @Movement.started -= m_Wrapper.m_CamraNewActionsCallbackInterface.OnMovement;
                @Movement.performed -= m_Wrapper.m_CamraNewActionsCallbackInterface.OnMovement;
                @Movement.canceled -= m_Wrapper.m_CamraNewActionsCallbackInterface.OnMovement;
                @RotateCamera.started -= m_Wrapper.m_CamraNewActionsCallbackInterface.OnRotateCamera;
                @RotateCamera.performed -= m_Wrapper.m_CamraNewActionsCallbackInterface.OnRotateCamera;
                @RotateCamera.canceled -= m_Wrapper.m_CamraNewActionsCallbackInterface.OnRotateCamera;
                @ZoomCamera.started -= m_Wrapper.m_CamraNewActionsCallbackInterface.OnZoomCamera;
                @ZoomCamera.performed -= m_Wrapper.m_CamraNewActionsCallbackInterface.OnZoomCamera;
                @ZoomCamera.canceled -= m_Wrapper.m_CamraNewActionsCallbackInterface.OnZoomCamera;
            }
            m_Wrapper.m_CamraNewActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Movement.started += instance.OnMovement;
                @Movement.performed += instance.OnMovement;
                @Movement.canceled += instance.OnMovement;
                @RotateCamera.started += instance.OnRotateCamera;
                @RotateCamera.performed += instance.OnRotateCamera;
                @RotateCamera.canceled += instance.OnRotateCamera;
                @ZoomCamera.started += instance.OnZoomCamera;
                @ZoomCamera.performed += instance.OnZoomCamera;
                @ZoomCamera.canceled += instance.OnZoomCamera;
            }
        }
    }
    public CamraNewActions @CamraNew => new CamraNewActions(this);
    public interface ICamraNewActions
    {
        void OnMovement(InputAction.CallbackContext context);
        void OnRotateCamera(InputAction.CallbackContext context);
        void OnZoomCamera(InputAction.CallbackContext context);
    }
}
